### ISSUE TITLE
OTA Updates Using Captive Portal Improvements: Better HTTP Handling

### ISSUE THREAD

**Issue by nfeuer** [ClusterDuck-Protocol/ClusterDuck-Protocol#160]
**Describe the solution you'd like**
Currently, it just reboots at the end of a successful update, which means the client is going to time-out eventually and doesn't give any feedback. So the client cant tell if the update actually worked or if something explode-rebooted

some reference links:
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/ota.html
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/app_image_format.html

Broken out from original OTA issue

**Comment by TimoWielink** [comment]
Also, need to look into interrupts from the Application Layer during OTA, Wifi keeps trying to connect and interrupts the upload of binary
