### ISSUE TITLE
OTA Updates Using LoRa

### ISSUE THREAD

**Issue by nfeuer** [ClusterDuck-Protocol/ClusterDuck-Protocol#162]
**Is your feature request related to a problem? Please describe.**
Once Duck devices are set up, it becomes extremely time-consuming to update the deployed devices. This issue scales significantly as you increase the number of devices you need to update. Therefore we need a solution to be able to remotely update devices. As the devices are all connected in a LoRa mesh network, using LoRa for the task is very attractive.

**Describe the solution you'd like**
Develop a protocol that allows devices to be updated over LoRa and be able to pass on update information to other devices in the network. It would be also useful to be able to target devices that need to be updated. 

**Describe alternatives you've considered**
This solution will require sending multiple packets and being able to stitch them back together. This is most likely the first step if there aren't any existing solutions out there.

**Comment by Evilgeniusnerd** [comment]
This works to create x amount of bins for flashing.  What is still needed is integration into CDP and the current duck OTA process. The idea setup would be to use some kind of device like a raspi as a local host server. The duck would connect to the network and check to see if there are any bin files to update the existing ducks firmware. 

https://github.com/Evilgeniusnerd/CDPBinUtility
