### ISSUE TITLE
index.h uses `b` and `body` as class names.

### ISSUE THREAD

**Issue by rolsen** [ClusterDuck-Protocol/ClusterDuck-Protocol#225]
src/include/index.h uses `b` as a class, but `b` is an [element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/b) already.

**Comment by rolsen** [comment]
Same for `body`.

**Comment by TimoWielink** [comment]
I can fix this ASAP

**Comment by krook** [comment]
Still an issue @TimoWielink @rolsen?

**Comment by rolsen** [comment]
Currently there's still some HTML tag names being used as a class:

`body`: https://github.com/Call-for-Code/ClusterDuck-Protocol/blob/3fa5d525b72417fffc32ee6663f8323ad0838019/src/include/index.h#L137 (and in other places)

`b`: https://github.com/Call-for-Code/ClusterDuck-Protocol/blob/3fa5d525b72417fffc32ee6663f8323ad0838019/src/include/index.h#L156

**Comment by faradaym** [comment]
fixed in #246
