### ISSUE TITLE
Routing over Reticulum?

### ISSUE THREAD

**Issue by samuk** [ClusterDuck-Protocol/ClusterDuck-Protocol#274]
**Describe the bug**
Transport level security vulnerabilities: https://www.youtube.com/watch?v=LBd-ewnjn8M

**To reproduce**
Steps to reproduce the behaviour:
See: https://www.youtube.com/watch?v=LBd-ewnjn8M

**Expected behaviour**
Messages are secure

**Additional context**

Where secure messaging is needed could you route the packets over reticulum: https://unsigned.io/projects/reticulum/

**Comment by nfeuer** [comment]
So I have seen Reticulum before and have been meaning to take a deeper dive. Looked really interesting. Been reading Mark Qvist's blog every now and then. @samuk have you used Reticulum before?

**Comment by samuk** [comment]
TBH I've been waiting for the Android & ESP32 stuff which has only come out in the last week or so. I plan to give it a go soon,

**Comment by nfeuer** [comment]
Definitely share your thoughts when you try it out. I think I would like to bring this up as a topic during our next town hall
