### ISSUE TITLE
huge numbers for duckType 

### ISSUE THREAD

**Issue by tqrahman** [ClusterDuck-Protocol/ClusterDuck-Protocol#282]
**Describe the bug**
some duckTypes of the messages are not normal in version 3. Some values we received are 162, 98, 210, 6.  

**To reproduce**
the data is shown from Owl_HQ

**Expected behavior**
the duckTypes should be 2 for MamaDucks and 1 for PapaDuck.

**Screenshots**
<img width="908" alt="Screen Shot 2022-06-03 at 12 07 14 PM" src="https://user-images.githubusercontent.com/17665316/171903656-bb6979b4-78e2-444a-b6e3-63740a8dfb28.png">

**Comment by faradaym** [comment]
Stale issue, hasn't been observed in v4
