### ISSUE TITLE
Wiki - Add instructions to create %USERPROFILE%\Documents\Arduino\libraries

### ISSUE THREAD

**Issue by micheljung** [ClusterDuck-Protocol/ClusterDuck-Protocol#287]
To which page do you want to add to the wiki?
[Windows installation](https://github.com/Call-for-Code/ClusterDuck-Protocol/wiki/windows#part-one-install-arduino-ide-on-windows)

What do you want to change/add?
After Installing the Arduino IDE, `%USERPROFILE%\Documents\Arduino\libraries` does not exist, so it needs to be created by the user. Without this directory, the script installation will fail.
Alternatively, and maybe more user-friendly, [the setup script](https://clusterduckprotocol.org/assets/Wiki_Script/windows.sh) could be extended so that it asks the user if he wants to create the directory if it's missing. Or it might just do it and risk that the user has specified it somewhere else.

Is your documentation related to a recent pull request or issue?
No

**Comment by faradaym** [comment]
out of date
