### ISSUE TITLE
Wiki - Restart Arduino IDE after adding Boards Manager URLs and after installing libraries

### ISSUE THREAD

**Issue by micheljung** [ClusterDuck-Protocol/ClusterDuck-Protocol#288]
To which page do you want to add to the wiki?
[Windows installation](https://github.com/Call-for-Code/ClusterDuck-Protocol/wiki/windows#part-one-install-arduino-ide-on-windows)

What do you want to change/add?
* After adding the Additional Boards Manager URLs, `ESP32` can't be found in the Boards Manager until the Arduino IDE is restarted. Or is there another way?
* After installing the libraries ([Part Two](https://github.com/Call-for-Code/ClusterDuck-Protocol/wiki/windows#part-two-install-libraries-and-dependencies)), the IDE must be restarted again before the examples are listed.

Is your documentation related to a recent pull request or issue?
No

**Comment by faradaym** [comment]
out of date
