### ISSUE TITLE
DuckDisplay does not support OLED displays on the CubeCell

### ISSUE THREAD

**Issue by amirna2** [ClusterDuck-Protocol/ClusterDuck-Protocol#295]
**Describe the bug**
When running CDP Duck example on the Heltec CubeCell GPS, the Duck Display APIs don't show anything on the display

**Expected behavior**
DuckDisplay should work or indicate an error if the display is not supported.

**Additional context**
The reason why it is not working is because the current implementation for DuckDisplay relies on the U8G2 library which doesn't support the SDD13006 OLED display found on the CubeCell.
The solution would be to port the DuckDisplay APIs to the Heltec provided display library. The DuckDisplay methods are generic enough that it should map pretty well. If no mapping exist, the method should return a "NOT SUPPORTED" error code.

**Comment by faradaym** [comment]
Possibly fixed, but plan to remove CubeCell support
