### ISSUE TITLE
Wiki - Update the Installation Instructions

### ISSUE THREAD

**Issue by ShivankAg** [ClusterDuck-Protocol/ClusterDuck-Protocol#337]
To which page do you want to add to the wiki?
- Install CDP > Installation Videos
- Install CDP > Arduino IDE > Windows

What do you want to change/add?
Currently in the videos, it shows that when you clone the github, it automatically installs the libraries. However, currently it does not do that and you need to run a separate python script to pull all the libraries down. The text on the wiki (Arduino IDE Pages) also implies this is the case (and the library installer is listed as a separate possible way to install the project, not as another required step).

I think the video should be updated to reflect this change. As well, the text on the Arduino IDE pages should list the library installations as a separate required step (rather than as a potential option to install the project).

Is your documentation related to a recent pull request or issue?
I had this issue when I was trying to get setup and got help in the slack.

**Comment by faradaym** [comment]
Videos were removed
