### ISSUE TITLE
Research ESPASYNCweb Forks

### ISSUE THREAD

**Issue by TimoWielink** [ClusterDuck-Protocol/ClusterDuck-Protocol#339]
**Describe the bug**
Me No Dev is not keeping his Fork up to date so we need to look into forkls that are updated

**Comment by amirna2** [comment]
This can probably be closed after 3.7 is released:
I am using a new fork of the project: `mathieucarbou/ESP Async WebServer@^2.7.0`
https://oss.carbou.me/ESPAsyncWebServer/

**Comment by amirna2** [comment]
Fixed in CDP 4.0.0
