### ISSUE TITLE
Stray code in dependency script causes compile error

### ISSUE THREAD

**Issue by amirna2** [ClusterDuck-Protocol/ClusterDuck-Protocol#345]
**Describe the bug**
The python dependency  script is broken. There is a redundant `except` block.
https://github.com/ClusterDuck-Protocol/ClusterDuck-Protocol/blob/master/cdp-dependency-automator-script/install-dependencies.py#L136C1-L142C26

**To reproduce**

```
python3 ./install-dependencies.py 
File "/Users/nathoo/dev/ClusterDuck-Protocol/cdp-dependency-automator-script/install-dependencies.py", line 79
    retry_count = 0
SyntaxError: expected 'except' or 'finally' block
```

**Expected behavior**
Script should run without error and the dependencies installed as expected

**Comment by tqrahman** [comment]
This issue was solved by merging with this recent PR https://github.com/ClusterDuck-Protocol/ClusterDuck-Protocol/pull/346
