### ISSUE TITLE
Update PlatformIO Wiki

### ISSUE THREAD

**Issue by tqrahman** [ClusterDuck-Protocol/ClusterDuck-Protocol#382]

**Comment by amirna2** [comment]
Note there is a developer guide already that provide instructions on how to use PlatformIO.
Maybe it's enough to just link that document in the wiki.
https://github.com/ClusterDuck-Protocol/ClusterDuck-Protocol/blob/master/DEVELOPER_GUIDE.md

**Comment by TimoWielink** [comment]
Lets discuss what Strucutre we want for CDP WIKI going forward

**Comment by tqrahman** [comment]
The Developer_Guide.md was using the CLI, we made one where you can also use VSCode IDE. It would be good to have both options. Nonetheless, here is the walkthrough [Installing PIO using the IDE](https://github.com/ClusterDuck-Protocol/ClusterDuck-Protocol/wiki/platformio#using-cli)
