### ISSUE TITLE
Doxygen Pipeline Still Failing

### ISSUE THREAD

**Issue by amirna2** [ClusterDuck-Protocol/ClusterDuck-Protocol#387]
When I merged CDP 4.0.1 to master, the doxygen.yml workflow still failed with some Access Denied issues:

https://github.com/ClusterDuck-Protocol/ClusterDuck-Protocol/actions/runs/8253841471/job/22576624953

There seems to be several issues here.
- It's not finding the docs/html folder which was removed because we don't want to version control the generated HTML files. Not sure why the action is looking for the HTML folder there and not the working directory which is the project root.
- The second issue is the access denied to the ClusterDuck github repo.

**Comment by faradaym** [comment]
fixed in #400
