### ISSUE TITLE
Remove some pages from the Wiki

### ISSUE THREAD

**Issue by amirna2** [ClusterDuck-Protocol/ClusterDuck-Protocol#388]
**IMPORTANT**  
Check the Wiki, developer's guide or ask the community on Slack before submitting a new ticket. You might find a solution to your issue there.

Also, please make use of [markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) to format your issue. This will make it easier for us to understand and help you. 

![image](https://github.com/ClusterDuck-Protocol/ClusterDuck-Protocol/assets/12193187/45bfe24c-f3a5-4a8e-8ee9-df5ffdf2c8ad)

The Developer resources pages could be removed.
- Design Document
- Message Handling
- Versioning
- Travis - Build Server

Versioning doesn't need explaining. We could simply state we are following semver and add a link to https://semver.org

Additionally we should link the Developer's Guide in that Developer Resource section.

**Comment by TimoWielink** [comment]
I will also take a look at this, start with outlining if we want to archive documentation for V3 and separate based on versions

**Comment by tqrahman** [comment]
The table of contents is simplified!
