### ISSUE TITLE
Refactor DuckRadio

### ISSUE THREAD

**Issue by amirna2** [ClusterDuck-Protocol/ClusterDuck-Protocol#410]
DuckRadio was modified to have all its methods be private and converted to a namespace rather than a singleton class.
The reason for this was so that DuckRadio could only be accessed through a Duck.

When a chat message is being sent in the mesh, it then calls into Duck to send the data, instead of lateral call to DuckRadio send method.

This change violates encapsulation principles as now we have 5 classes being friends of DuckRadio only so they can access the now private methods.

Additionally we can't build unit tests for DuckRadio as all methods are private. To test those methods would require us to wrap the `private:` section with a macro to make them publicly available when unit testing. Again a hack to fix a problem cause by a design issue.

The solution here is to revert back to DuckRadio being a singleton..update all code inside CDP that would need to send data into the mesh. Additionally add unit tests for all public methods of DuckRadio

**Comment by faradaym** [comment]
Resolved in #415
