### ISSUE TITLE
Test DuckDisplay

### ISSUE THREAD

**Issue by amirna2** [ClusterDuck-Protocol/ClusterDuck-Protocol#416]
A user reported a crash/reboot on the Heltec LoRa 32 V3 when Display is enabled and he tried to use it.

**Comment by amirna2** [comment]
I tested this with 4.1.0 and it is working as expected.
Adding this to the DuckLink `setup()` after the Duck was initialized
```
  DuckDisplay* display = NULL;
  display = DuckDisplay::getInstance();
  display->setupDisplay(duck.getType(), devId);
  display->showDefaultScreen();
```

**Comment by tqrahman** [comment]
I tested it in v3 and it works. I have not experienced any crash/reboot.
 
![IMG_2662](https://github.com/ClusterDuck-Protocol/ClusterDuck-Protocol/assets/17665316/2969be63-a0c9-4e7d-8a24-243c19e521b7)
