### ISSUE TITLE
CDP Crypto Library

### ISSUE THREAD

**Issue by tqrahman** [ClusterDuck-Protocol/ClusterDuck-Protocol#425]
**Describe the bug**
The library for Crypto is not the correct version. The current version for CDP is 0.4.0 but it doesn't work. The version that works is 0.2.0.

It gives an error with 0.4.0 saying AES.h is not found.

We were running it in Tbeam (SX176x LoRa chip)

**To reproduce**
Install ClusterDuck Protocol and upload a MamaDuck example in 1.Ducks -> MamaDuck.ino

**Expected behavior**

**Screenshots**

**Comment by faradaym** [comment]
The latest release of CDP is now available in Arduino IDE, and is compatible with Crypto 0.4.0
