### ISSUE TITLE
AXP code not working for the Tbeam SX1262 chip. 

### ISSUE THREAD

**Issue by tqrahman** [ClusterDuck-Protocol/ClusterDuck-Protocol#432]
**Describe the bug**
The current code for to get battery usage for the LoRa SX126x chip not working. 

**To reproduce**
Upload the [TBeam-AXP-Example](https://github.com/ClusterDuck-Protocol/ClusterDuck-Protocol/tree/master/examples/6.TTGO-TBeam-Examples/TBeam-AXP-Example) in the sx126s chip board. When the packets are sent, the battery voltage, board temperature is -3.

**Expected behavior**
It should provide the battery voltage, and board temperature

**Screenshots**

**Additional context (please complete)**
- MCU: T-Beam
- Wireless module type - LoRa SX1262

**Comment by faradaym** [comment]
As noted in #433 , this  issue is no longer relevant
