### ISSUE TITLE
Device Names in PlatformIO example .inis are Inconsistent

### ISSUE THREAD

**Issue by faradaym** [ClusterDuck-Protocol/ClusterDuck-Protocol#454]
In some example files, the pio device names for the `default_envs` variable are outdated. For example, TTGO T-Beam v1 in `Basic-Ducks/MamaDuck`. Make sure all device names in all PlatformIO files are up to date

**Comment by marhabac33** [comment]
@faradaym I can work on this. 

should it be `default_envs = local_ttgo_lora32_v1` instead of `default_envs = local_ttgo_t_beam`

**Comment by marhabac33** [comment]
@faradaym checking in if my understanding above is correct

**Comment by faradaym** [comment]
@marhabac33 yes, that is correct!

**Comment by marhabac33** [comment]
@faradaym https://github.com/ClusterDuck-Protocol/ClusterDuck-Protocol/pull/458 is up
